#!/usr/bin/env node
/**
 * Generates src/data/*.gen.ts from AlgoSplit's engine data.
 *
 * Inputs (produced from the AlgoSplit repo):
 *   - algosplit-data.json      { regions, patterns, profiles }  (python dump)
 *   - algosplit-exercises.json [ { name, pattern, equipment?, unilateral? } ]
 *
 * Usage: node scripts/generate-data.js <data.json> <exercises.json>
 */
const fs = require('fs');
const path = require('path');

const [, , dataPath, exercisesPath] = process.argv;
if (!dataPath || !exercisesPath) {
  console.error('usage: generate-data.js <algosplit-data.json> <algosplit-exercises.json>');
  process.exit(1);
}

const { regions, patterns, profiles } = JSON.parse(fs.readFileSync(dataPath, 'utf8'));
const exercises = JSON.parse(fs.readFileSync(exercisesPath, 'utf8'));

const outDir = path.join(__dirname, '..', 'src', 'data');

const header = (what) =>
  `// GENERATED by scripts/generate-data.js from AlgoSplit (${what}). Do not edit by hand.\n\n`;

// ── muscleRegions.gen.ts ────────────────────────────────────────────────────
const regionEntries = Object.entries(regions)
  .map(
    ([id, r]) =>
      `  ${JSON.stringify(id)}: { displayName: ${JSON.stringify(r.display_name)}, parentGroup: ${JSON.stringify(
        r.parent_group
      )}, leverage: ${JSON.stringify(r.leverage)}, damageTier: ${JSON.stringify(
        r.damage_tier
      )}, recoveryModifier: ${r.recovery_modifier}, axialContributor: ${r.axial_fatigue_contributor} },`
  )
  .join('\n');

fs.writeFileSync(
  path.join(outDir, 'muscleRegions.gen.ts'),
  header('backend/core/muscle_regions.py') +
    `export interface MuscleRegionMeta {
  displayName: string;
  parentGroup: string;
  /** S = short, M = mid, L = long — optimal force production position */
  leverage: 'S' | 'M' | 'L';
  /** '+' high damage / slow recovery, '0' neutral, '-' low damage */
  damageTier: '+' | '0' | '-';
  /** Multiplies the base 48h stimulus/recovery window */
  recoveryModifier: number;
  axialContributor: boolean;
}

export const MUSCLE_REGIONS: Record<string, MuscleRegionMeta> = {
${regionEntries}
};
`
);

// ── movementPatterns.gen.ts ─────────────────────────────────────────────────
const patternEntries = Object.entries(patterns)
  .map(([id, p]) => {
    const tiers = ['prime', 'secondary', 'tertiary', 'quaternary']
      .map((t) => `${t}: ${JSON.stringify(p[t] ?? {})}`)
      .join(', ');
    const profile = profiles[id] ?? 'mid';
    return `  ${JSON.stringify(id)}: { ${tiers}, axialLoad: ${p.axial_load ?? 0}, resistanceProfile: ${JSON.stringify(
      profile
    )} },`;
  })
  .join('\n');

fs.writeFileSync(
  path.join(outDir, 'movementPatterns.gen.ts'),
  header('backend/core/granular_patterns.py + DEFAULT_RESISTANCE_PROFILES') +
    `export interface MovementPattern {
  prime: Record<string, number>;
  secondary: Record<string, number>;
  tertiary: Record<string, number>;
  quaternary: Record<string, number>;
  /** 0–1 spinal/axial loading of the movement */
  axialLoad: number;
  resistanceProfile: 'ascending' | 'mid' | 'descending';
}

export const MOVEMENT_PATTERNS: Record<string, MovementPattern> = {
${patternEntries}
};
`
);

// ── exerciseCatalog.gen.ts ──────────────────────────────────────────────────
const slug = (name) =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_|_$/g, '');

const seenIds = new Set();
const catalogEntries = exercises
  .filter((e) => patterns[e.pattern]) // drop anything referencing an unknown pattern
  .map((e) => {
    let id = slug(e.name);
    while (seenIds.has(id)) id = `${id}_x`;
    seenIds.add(id);
    const parts = [
      `id: ${JSON.stringify(id)}`,
      `name: ${JSON.stringify(e.name)}`,
      `pattern: ${JSON.stringify(e.pattern)}`,
    ];
    if (e.equipment) parts.push(`equipment: ${JSON.stringify(e.equipment)}`);
    if (e.unilateral) parts.push(`unilateral: true`);
    return `  { ${parts.join(', ')} },`;
  })
  .join('\n');

fs.writeFileSync(
  path.join(outDir, 'exerciseCatalog.gen.ts'),
  header('app/src/data/exercises.ts (307 exercises)') +
    `export interface CatalogEntry {
  id: string;
  name: string;
  /** Key into MOVEMENT_PATTERNS */
  pattern: string;
  equipment?: string;
  unilateral?: boolean;
}

export const EXERCISE_CATALOG: CatalogEntry[] = [
${catalogEntries}
];
`
);

console.log(
  `wrote ${Object.keys(regions).length} regions, ${Object.keys(patterns).length} patterns, ${seenIds.size} exercises`
);
