export const HELP_CONTENT: Record<string, { title: string; body: string }> = {
  'dashboard.bodyMap': {
    title: 'Body Stimulus Map',
    body: 'Shows your actualized net stimulus over the last week per muscle region. Colors are absolute, not relative — the same color always means the same amount of growth, so you can compare across days and splits.\n\nThe scale is anchored to how the engine actually models growth:\n\nGrey — at or below maintenance (no net growth).\n\nBlue / teal — building: positive but modest stimulus.\n\nGreen — growing: a solid, productive weekly dose.\n\nDeep green — optimal: near the practical weekly ceiling.\n\nMost muscles sit in the cooler range; green means that region is genuinely being grown, not just trained.',
  },
  'dashboard.dials': {
    title: 'Performance Dials',
    body: 'Three gauges that summarize different aspects of the same week:\n\nStimulus — the mean dose adequacy across every muscle you trained. 100 means every trained muscle is at or above the "Growing" threshold; a strong split typically reads 40–70 because most splits leave some muscles undercooked. Bright muscles on the body map lift this number, dim trained muscles drag it down.\n\nProgress — whether you\'re progressing load or effort over time, comparing your two most recent matching workouts.\n\nHeadroom — remaining whole-body recovery capacity, averaged across all 29 regions. Untrained regions contribute full headroom (they\'re rested); trained regions consume capacity in proportion to their fatigue. A one-muscle workout reads high because most of your body is still rested. A heavy week with many fried regions reads low.',
  },
  'splits.overview': {
    title: 'Splits',
    body: 'A split is your weekly training plan — which muscles you train on which days. Create a split, add sessions with exercises, and the engine will simulate a full cycle to show how much stimulus each muscle actually receives after accounting for fatigue, recovery, and diminishing returns.',
  },
  'splits.analysisOverview': {
    title: 'Split Analysis',
    body: 'Your split is simulated over one full cycle to estimate weekly stimulus per muscle.\n\nAvg Stimulus — the mean net stimulus across all 29 muscle regions. Higher is more volume, but diminishing returns apply.\n\nMuscles Trained — how many of the 29 regions receive any stimulus at all.\n\nTop / Lowest — highlights your strongest and weakest muscle. Large gaps suggest imbalance.',
  },
  'splits.stimulusByGroup': {
    title: 'Stimulus by Region',
    body: 'Each bar shows the weekly stimulus for a muscle region after a full simulated cycle.\n\nStimulus is the hypertrophic signal generated by training — but it only lasts for the stimulus duration window (typically 36–72h). After that window closes, atrophy begins. Your muscles are either growing or shrinking; there is no coasting.\n\nRAW stimulus is what you accumulate during a session. NET stimulus is what remains after subtracting the atrophy that occurs between sessions. The gap between RAW and NET is larger when sessions for the same muscle are spread far apart, because more atrophy accrues before the next training bout.\n\nBar color uses the same absolute scale as the body map (grey = maintenance, green = growing, deep green = optimal), so a green bar always means real growth. Bar length is relative to the largest bar, just for visual comparison.',
  },
  'splits.regionsTabs': {
    title: 'Regions & Breakdown',
    body: 'Regions — shows net stimulus grouped by muscle (chest, back, quads, etc.). Green bars are above maintenance, red bars are below.\n\nBreakdown — shows how stimulus was built set-by-set across each session, including fatigue decay and recovery penalties. Useful for spotting which sets are giving diminishing returns.',
  },
  'splits.detailedAnalysis': {
    title: 'Analysis Settings',
    body: 'These settings tune how the engine simulates your split:\n\nDataset — which research curve to use for diminishing returns on volume. Schoenfeld is conservative, Pelland more optimistic, Average blends both.\n\nCycle Length — total days in your split including rest days (e.g. PPL + rest = 7, 5-day rotation = 5).\n\nStimulus Duration — how many hours a muscle stays in a hypertrophic state after training (typically 36–72h).\n\nMaintenance Volume — sets per muscle done ONCE per week needed to maintain current size (net zero). Below this = atrophy, above = growth. This means sets in a single session, not spread across multiple days — 3 sets on 3 separate days could still produce positive stimulus.',
  },
  'exercises.unilateral': {
    title: 'Unilateral (UNI)',
    body: 'Marks an exercise as single-limb (e.g. one-arm rows, lunges). Unilateral exercises allow for greater motor unit recruitment per side',
  },
  'exercises.customOverview': {
    title: 'Custom Exercises',
    body: 'Create custom exercise definitions to override the built-in pattern matching. Define exactly which muscles a movement recruits, its resistance profile, and whether it is unilateral. Useful for unusual exercises or when the auto-classifier gets it wrong.',
  },
  'exercises.muscleTargets': {
    title: 'Custom Muscle Targets',
    body: 'Define exactly which muscles a movement pattern recruits and how much. Weights are split across Prime (main movers), Secondary, and Tertiary tiers. Total must equal 1.00.',
  },
  'exercises.resistanceProfile': {
    title: 'Resistance Profile',
    body: 'Where in the range of motion the exercise is hardest.\n\nAscending — hardest at top / shortened position (e.g. cables, machines).\n\nMid-range — hardest in the middle (most free weight exercises).\n\nDescending — hardest at the bottom / stretched position.',
  },
  'compare.overview': {
    title: 'Compare Splits',
    body: 'Compare all key metrics across 2–3 splits side by side. Evaluate trade-offs between balance (even stimulus across all muscles) and specialization (prioritizing certain muscle groups).',
  },
  'history.overview': {
    title: 'History',
    body: 'Every workout you log is tracked here. Switch between the workout log and the progression chart to see your training history and how your lifts are trending over time.',
  },
  'history.progressChart': {
    title: 'Progression Chart',
    body: 'Load on the Y-axis, time on the X-axis. The color of the spline shows how your RIR (reps in reserve) has changed at a given weight via a proprietary progression score. A shifting color at the same weight means you\'re getting stronger without adding load.',
  },
};
