// GENERATED by scripts/generate-data.js from AlgoSplit (backend/core/granular_patterns.py + DEFAULT_RESISTANCE_PROFILES). Do not edit by hand.

export interface MovementPattern {
  prime: Record<string, number>;
  secondary: Record<string, number>;
  tertiary: Record<string, number>;
  quaternary: Record<string, number>;
  /** 0–1 spinal/axial loading of the movement */
  axialLoad: number;
  resistanceProfile: 'ascending' | 'mid' | 'descending';
}

export const MOVEMENT_PATTERNS: Record<string, MovementPattern> = {
  "humeral_adduction_compound": { prime: {"sternocostal":0.7}, secondary: {"clavicular":0.15,"anterior_deltoid":0.1}, tertiary: {"triceps_lateral_medial":0.05}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "clavicular_humeral_adduction_compound": { prime: {"clavicular":0.55}, secondary: {"sternocostal":0.2,"anterior_deltoid":0.2}, tertiary: {"triceps_lateral_medial":0.05}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "humeral_adduction_isolation": { prime: {"sternocostal":0.8}, secondary: {"clavicular":0.1,"anterior_deltoid":0.1}, tertiary: {}, quaternary: {}, axialLoad: 0, resistanceProfile: "descending" },
  "clavicular_humeral_adduction_isolation": { prime: {"clavicular":0.7}, secondary: {"anterior_deltoid":0.2,"sternocostal":0.1}, tertiary: {}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "pronated_vertical_press_compound": { prime: {"anterior_deltoid":0.45,"lateral_deltoid":0.35}, secondary: {"clavicular":0.1,"triceps_lateral_medial":0.1}, tertiary: {}, quaternary: {}, axialLoad: 0.3, resistanceProfile: "mid" },
  "neutral_vertical_press_compound": { prime: {"anterior_deltoid":0.65,"clavicular":0.25}, secondary: {"lateral_deltoid":0.05,"triceps_lateral_medial":0.05}, tertiary: {}, quaternary: {}, axialLoad: 0.3, resistanceProfile: "mid" },
  "shoulder_flexion_isolation": { prime: {"anterior_deltoid":0.9}, secondary: {"clavicular":0.1}, tertiary: {}, quaternary: {}, axialLoad: 0, resistanceProfile: "descending" },
  "shoulder_abduction_isolation": { prime: {"lateral_deltoid":0.85}, secondary: {"anterior_deltoid":0.05,"posterior_deltoid":0.05,"trapezius":0.05}, tertiary: {}, quaternary: {}, axialLoad: 0, resistanceProfile: "descending" },
  "shoulder_transverse_abduction_isolation": { prime: {"posterior_deltoid":0.8}, secondary: {"trapezius":0.1}, tertiary: {"rhomboids":0.05}, quaternary: {}, axialLoad: 0, resistanceProfile: "descending" },
  "transverse_adduction_compound": { prime: {"iliac_lats":0.7}, secondary: {"trapezius":0.05,"rhomboids":0.05,"posterior_deltoid":0.15}, tertiary: {"biceps_brachii":0.05,"brachialis":0.03,"brachioradialis":0.02}, quaternary: {}, axialLoad: 0.2, resistanceProfile: "mid" },
  "transverse_adduction_isolation": { prime: {"iliac_lats":0.8}, secondary: {"posterior_deltoid":0.1}, tertiary: {"triceps_long_head":0.05,"sternocostal":0.05}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "sagittal_adduction_compound": { prime: {"thoracic_lats":0.7}, secondary: {"trapezius":0.05,"rhomboids":0.05,"posterior_deltoid":0.15}, tertiary: {"biceps_brachii":0.05,"brachialis":0.03,"brachioradialis":0.02}, quaternary: {}, axialLoad: 0.2, resistanceProfile: "mid" },
  "sagittal_adduction_isolation": { prime: {"thoracic_lats":0.8}, secondary: {"posterior_deltoid":0.1}, tertiary: {"triceps_long_head":0.05,"sternocostal":0.05}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "scapular_retraction_compound": { prime: {"trapezius":0.5,"rhomboids":0.2}, secondary: {"thoracic_lats":0.05,"posterior_deltoid":0.1}, tertiary: {"biceps_brachii":0.05,"brachialis":0.03,"brachioradialis":0.02}, quaternary: {}, axialLoad: 0.4, resistanceProfile: "mid" },
  "scapular_retraction_isolation": { prime: {"trapezius":0.6,"rhomboids":0.3}, secondary: {"posterior_deltoid":0.1}, tertiary: {}, quaternary: {}, axialLoad: 0.1, resistanceProfile: "mid" },
  "squat_compound": { prime: {"vasti":0.35,"rectus_femoris":0.15,"glute_max":0.25}, secondary: {"hip_adductors":0.1,"hip_extensors":0.05}, tertiary: {"spinal_erectors":0.05,"deep_core":0.05}, quaternary: {}, axialLoad: 0.8, resistanceProfile: "mid" },
  "hinge_compound": { prime: {"hip_extensors":0.35,"glute_max":0.25,"spinal_erectors":0.2}, secondary: {"thoracic_lats":0.05,"iliac_lats":0.05,"trapezius":0.05}, tertiary: {"deep_core":0.05}, quaternary: {}, axialLoad: 1, resistanceProfile: "mid" },
  "lunge_compound": { prime: {"vasti":0.3,"rectus_femoris":0.15,"glute_max":0.25}, secondary: {"hip_extensors":0.15,"glute_med_min":0.05}, tertiary: {"hip_adductors":0.05,"deep_core":0.05}, quaternary: {}, axialLoad: 0.3, resistanceProfile: "mid" },
  "knee_extension_isolation": { prime: {"vasti":0.2,"rectus_femoris":0.8}, secondary: {}, tertiary: {}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "knee_flexion_isolation": { prime: {"knee_flexors":0.65,"hip_extensors":0.2}, secondary: {"gastrocnemius":0.15}, tertiary: {}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "hip_extension_isolation": { prime: {"glute_max":0.8}, secondary: {"hip_extensors":0.15}, tertiary: {"spinal_erectors":0.05}, quaternary: {}, axialLoad: 0.1, resistanceProfile: "mid" },
  "hip_abduction_isolation": { prime: {"glute_med_min":0.85}, secondary: {"glute_max":0.1}, tertiary: {"hip_adductors":0.05}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "hip_adduction_isolation": { prime: {"hip_adductors":0.9}, secondary: {"glute_max":0.05}, tertiary: {"hip_extensors":0.05}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "ankle_plantarflexion_isolation": { prime: {"gastrocnemius":0.55,"soleus":0.45}, secondary: {}, tertiary: {}, quaternary: {}, axialLoad: 0.1, resistanceProfile: "mid" },
  "elbow_flexion_isolation": { prime: {"biceps_brachii":0.85,"brachialis":0.1}, secondary: {"brachioradialis":0.05}, tertiary: {}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "pronated_elbow_flexion_isolation": { prime: {"brachioradialis":0.55,"brachialis":0.25,"biceps_brachii":0.15}, secondary: {"wrist_extensors":0.05}, tertiary: {}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "tricep_compound": { prime: {"triceps_lateral_medial":0.5}, secondary: {"triceps_long_head":0.15,"sternocostal":0.2}, tertiary: {"anterior_deltoid":0.1,"clavicular":0.05}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "elbow_extension_isolation": { prime: {"triceps_long_head":0.7,"triceps_lateral_medial":0.3}, secondary: {}, tertiary: {}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "overhead_elbow_extension_isolation": { prime: {"triceps_lateral_medial":0.85}, secondary: {"triceps_long_head":0.15}, tertiary: {}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "wrist_flexion_isolation": { prime: {"wrist_flexors":0.9}, secondary: {"brachioradialis":0.1}, tertiary: {}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "wrist_extension_isolation": { prime: {"wrist_extensors":0.9}, secondary: {"brachioradialis":0.1}, tertiary: {}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "spinal_flexion": { prime: {"anterior_core":0.75}, secondary: {"lateral_core":0.15}, tertiary: {"rectus_femoris":0.1}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "leg_raise": { prime: {"anterior_core":0.6,"rectus_femoris":0.25}, secondary: {"lateral_core":0.1}, tertiary: {"hip_adductors":0.05}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "anti_extension": { prime: {"anterior_core":0.7,"deep_core":0.2}, secondary: {"lateral_core":0.1}, tertiary: {}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "spinal_extension": { prime: {"spinal_erectors":0.85}, secondary: {"glute_max":0.1}, tertiary: {"hip_extensors":0.05}, quaternary: {}, axialLoad: 0.5, resistanceProfile: "mid" },
  "trunk_rotation": { prime: {"lateral_core":0.85}, secondary: {"anterior_core":0.1}, tertiary: {"deep_core":0.05}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "anti_rotation": { prime: {"lateral_core":0.6,"deep_core":0.25}, secondary: {"anterior_core":0.1}, tertiary: {"glute_med_min":0.05}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
  "lateral_flexion": { prime: {"lateral_core":0.85}, secondary: {"spinal_erectors":0.1}, tertiary: {"deep_core":0.05}, quaternary: {}, axialLoad: 0, resistanceProfile: "mid" },
};
