// GENERATED by scripts/generate-data.js from AlgoSplit (backend/core/muscle_regions.py). Do not edit by hand.

export interface MuscleRegionMeta {
  displayName: string;
  parentGroup: string;
  /** S = short, M = mid, L = long — optimal force production position */
  leverage: 'S' | 'M' | 'L';
  /** '+' high damage / slow recovery, '0' neutral, '-' low damage */
  damageTier: '+' | '0' | '-';
  /** Multiplies the base 48h stimulus/recovery window */
  recoveryModifier: number;
  axialContributor: boolean;
}

export const MUSCLE_REGIONS: Record<string, MuscleRegionMeta> = {
  "clavicular": { displayName: "Upper Chest", parentGroup: "chest", leverage: "M", damageTier: "-", recoveryModifier: 1, axialContributor: false },
  "sternocostal": { displayName: "Mid-Lower Chest", parentGroup: "chest", leverage: "M", damageTier: "-", recoveryModifier: 1, axialContributor: false },
  "anterior_deltoid": { displayName: "Front Delt", parentGroup: "shoulders", leverage: "L", damageTier: "0", recoveryModifier: 1, axialContributor: false },
  "lateral_deltoid": { displayName: "Side Delt", parentGroup: "shoulders", leverage: "M", damageTier: "0", recoveryModifier: 1, axialContributor: false },
  "posterior_deltoid": { displayName: "Rear Delt", parentGroup: "shoulders", leverage: "L", damageTier: "0", recoveryModifier: 1, axialContributor: false },
  "trapezius": { displayName: "Traps", parentGroup: "upper_back", leverage: "L", damageTier: "0", recoveryModifier: 1, axialContributor: false },
  "rhomboids": { displayName: "Rhomboids", parentGroup: "upper_back", leverage: "L", damageTier: "0", recoveryModifier: 1, axialContributor: false },
  "spinal_erectors": { displayName: "Lower Back", parentGroup: "lower_back", leverage: "S", damageTier: "+", recoveryModifier: 1.2, axialContributor: true },
  "thoracic_lats": { displayName: "Upper Lats", parentGroup: "lats", leverage: "S", damageTier: "0", recoveryModifier: 1, axialContributor: false },
  "iliac_lats": { displayName: "Lower Lats", parentGroup: "lats", leverage: "S", damageTier: "0", recoveryModifier: 1, axialContributor: false },
  "biceps_brachii": { displayName: "Biceps", parentGroup: "elbow_flexors", leverage: "L", damageTier: "-", recoveryModifier: 0.9, axialContributor: false },
  "brachialis": { displayName: "Brachialis", parentGroup: "elbow_flexors", leverage: "S", damageTier: "-", recoveryModifier: 0.9, axialContributor: false },
  "brachioradialis": { displayName: "Brachioradialis", parentGroup: "elbow_flexors", leverage: "S", damageTier: "+", recoveryModifier: 1.1, axialContributor: false },
  "triceps_long_head": { displayName: "Triceps Long Head", parentGroup: "triceps", leverage: "S", damageTier: "-", recoveryModifier: 0.9, axialContributor: false },
  "triceps_lateral_medial": { displayName: "Triceps Lateral/Medial", parentGroup: "triceps", leverage: "S", damageTier: "-", recoveryModifier: 0.9, axialContributor: false },
  "wrist_flexors": { displayName: "Wrist Flexors", parentGroup: "forearms", leverage: "L", damageTier: "+", recoveryModifier: 1.1, axialContributor: false },
  "wrist_extensors": { displayName: "Wrist Extensors", parentGroup: "forearms", leverage: "L", damageTier: "+", recoveryModifier: 1.1, axialContributor: false },
  "glute_max": { displayName: "Gluteus Maximus", parentGroup: "glutes", leverage: "S", damageTier: "0", recoveryModifier: 1, axialContributor: false },
  "glute_med_min": { displayName: "Gluteus Medius/Minimus", parentGroup: "glutes", leverage: "S", damageTier: "0", recoveryModifier: 1, axialContributor: false },
  "vasti": { displayName: "Vastus Group", parentGroup: "quads", leverage: "L", damageTier: "+", recoveryModifier: 1.15, axialContributor: false },
  "rectus_femoris": { displayName: "Rectus Femoris", parentGroup: "quads", leverage: "L", damageTier: "+", recoveryModifier: 1.15, axialContributor: false },
  "hip_extensors": { displayName: "Hamstrings (Proximal)", parentGroup: "hamstrings", leverage: "L", damageTier: "-", recoveryModifier: 1, axialContributor: false },
  "knee_flexors": { displayName: "Hamstrings (Distal)", parentGroup: "hamstrings", leverage: "L", damageTier: "-", recoveryModifier: 1, axialContributor: false },
  "gastrocnemius": { displayName: "Gastrocnemius", parentGroup: "calves", leverage: "L", damageTier: "+", recoveryModifier: 1.1, axialContributor: false },
  "soleus": { displayName: "Soleus", parentGroup: "calves", leverage: "L", damageTier: "+", recoveryModifier: 1.1, axialContributor: false },
  "hip_adductors": { displayName: "Hip Adductors", parentGroup: "adductors", leverage: "L", damageTier: "0", recoveryModifier: 1, axialContributor: false },
  "anterior_core": { displayName: "Abs", parentGroup: "abs", leverage: "L", damageTier: "+", recoveryModifier: 1.1, axialContributor: false },
  "lateral_core": { displayName: "Obliques", parentGroup: "abs", leverage: "L", damageTier: "+", recoveryModifier: 1.1, axialContributor: false },
  "deep_core": { displayName: "Transverse Abdominis", parentGroup: "abs", leverage: "L", damageTier: "+", recoveryModifier: 1, axialContributor: true },
};
